apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-13T15:38:52Z"
  labels:
    run: nginx
  name: nginx
  namespace: user-13
  resourceVersion: "2521053"
  selfLink: /api/v1/namespaces/user-13/pods/nginx
  uid: bfd05768-ee86-4b91-876b-1b91f8a2be5c
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: htmldir
    
  - image: busybox
    name: busybox
    env:
    - name: msg
      value: it's too cold!! 
    command: [ "/bin/sh"]
    args: ["-c",  "while true; do echo $msg >>/html/index.html; sleep 10; done"]
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    volumeMounts:
    - mountPath: /html
      name: htmldir
    livenessProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 1
      periodSeconds: 10
    startupProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 30
      periodSeconds: 10
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-esun-lecture-1-pool-4-4303c2db-4qfs
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: htmldir
    emptyDir: {}
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-01-13T15:38:52Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-01-13T15:38:54Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-01-13T15:38:54Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-01-13T15:38:52Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://895f31a3dce69c8c0386786ae6991a4b4d8d2593ac17d0420599b647324abb54
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:10b8cc432d56da8b61b070f4c7d2543a9ed17c2b23010b43af434fd40e2ca4aa
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-01-13T15:38:53Z"
  hostIP: 10.170.15.193
  phase: Running
  podIP: 10.60.7.10
  podIPs:
  - ip: 10.60.7.10
  qosClass: BestEffort
  startTime: "2021-01-13T15:38:52Z"
